
# XXX Native Events

BUTTON1 = '<Button-1>'

COMBOBOXSELECTED = '<<ComboboxSelected>>'

DOUBLECLICK1 = '<Double-1>'

MOTION = '<Motion>'

# XXX Custom Events

BACIAS_COMBO_CHANGE = '<<BACIAS_COMBO_CHANGE>>'

UV_COMBO_CHANGE = '<<UV_COMBO_CHANGE>>'

CLASSIFICATION_COMBO_CHANGE = '<<CLASSIFICATION_COMBO_CHANGE>>'

DETAIL_EVENT = '<<DETAIL_EVENT>>'

MARKER_CLICK = '<<MARKER_CLICK>>'
